### ISSUE TITLE
DB built with prepare_exSTRa_input_db.R different from repeat_expansion_disorders_hg38.txt.

### ISSUE THREAD

**Issue by rafaelmguedes** [bahlolab/exSTRa#63]
Hi
I used `prepare_exSTRa_input_db.R` to build a hg38 db file, but the retrieved data (motif, strand) is different in genes that are already available in pre-built `repeat_expansion_disorders_hg38.txt`, although they have the same coordinates.
Some examples for C9orf72, FMR1 and NOP56:
`````
locus	long_name	OMIM	inheritance	gene	location	gene_region	motif	norm_low	norm_up	aff_low	aff_up	aff_more	strand	chrom	start	end	copyNum	perMatch	perIndel	STR_size_bp	score_size	strcat
chr9_27573484_GCCCCG	chr9_27573484_GCCCCG	NA	NA	C9orf72	NA	intronic	GCCCCG	NA	NA	NA	NA	NA	+	chr9	27573485	27573546	10.8	74	65	NA	NA
FTDALS1	Amyotrophic lateral sclerosis-frontotemporal dementia	105550	AD	C9orf72	9p21	intron	GGGGCC	2	19	250	1600	FALSE	-	chr9	27573485	27573546	10.74	8	62	NA	http://strcat.teamerlich.org/chart/chr9/27573483/27573544
chrX_147912036_GGC	chrX_147912036_GGC	NA	NA	FMR1	NA	UTR5	GGC	NA	NA	NA	NA	NA	+	chrX	147912037	147912111	25	90	5	75	NA	NA
FRAXA	Fragile-X site A	309550	X	FMR1	Xq27.3	5'UTR	CGG	6	54	200	1000	TRUE	+	chrX	147912037	147912111	25	90	5	75	NA	http://strcat.teamerlich.org/chart/chrX/146993555/146993629
chr20_2652732_GGGCCT	chr20_2652732_GGGCCT	NA	NA	NOP56	NA	intronic	GGGCCT	NA	NA	NA	NA	NA	+	chr20	2652733	2652775	7.2	97	0	43	NA	NA
SCA36	Spinocerebellar ataxia 36	614153	AD	NOP56	20p13	intron	GGCCTG	3	8	1500	2500	FALSE	+	chr20	2652733	2652775	7.2	97	0	43	NA	http://strcat.teamerlich.org/chart/chr20/2633379/2633421
``````
Was `repeat_expansion_disorders_hg38.txt` further manually processed?
Is there any new version other than the available at devel_bennett branch from 2019 ?
Could you please indicate the obligatory and informational only columns?

Thank You!

**Comment by trickytank** [comment]
Hi @rafaelmguedes,

Sorry for the late reply. Just getting onto this project again now. 

**FRAXA** and **SCA36** have the equivalent motif, just starting on a different base. 

GGC is just CGG starting on the second base. 
GGGCCT is just GGCCTG starting on the sixth base. 

For **FTDALS1**, the locus is marked on the negative strand in our database. This is because the gene is on the negative strand. GCCCCG on the positive strand is CGGGGC on the negative strand. Adjusting the starting base, this can be seen to be equivalent to GGGGCC.
